repo_url: https://dar-internal.googlesource.com/nl2code-dataset
dataset_config: cymbalshop/dataset.json
database_config: configs/db/nl2code_postgres.yaml
model_config: configs/model/base_nl2code_model.yaml
prompt_generator: 'NOOPGenerator'
dbcodegen_target: localhost:11876
project_name: astana-evaluation
instance_name: nl2code
database_name: cymbalShop
llmrater:
  gcp_project_location: "us-central1"
  gcp_project_id: "astana-evaluation"
  model: "gemini-1.5-pro-001"