dataset_config: ../datasets/bat/db_hr.json
database_config: configs/db/postgres.yaml
model_config: configs/model/base_gemini_model.yaml
prompt_generator: 'DBSchemaGenerator'
dialect: 'postgres'
eval_ids: []
scorers: 
  exact_match:
  recall_match:
  vertexmatcher:
    gcp_project_location: "us-central1"
    gcp_project_id: "cloud-db-nl2sql"
    model: "gemini-1.0-pro-001"
  llmrater:
    gcp_project_location: "us-central1"
    gcp_project_id: "cloud-db-nl2sql"
    model: "gemini-1.5-pro-001"
