############################################################
### Dataset / Eval Items
############################################################
# The JSON list of prompts / golden SQLs and eval attributes for the run
dataset_config: datasets/bird/prompts.json
### Database Info
# The YAML config for the database connection information
database_configs:
 - datasets/bird/db_configs/sqlite.yaml
# The dialect that the dataset_config will be filtered by. Only one can be
# specified at a time (per run). See above for list of supported Dialects
dialects:
 - sqlite
query_types:
 - dql
#
#
############################################################
### Prompt and Generation Modules
############################################################
# The YAML config for the model to be used for generation.
model_config: datasets/model_configs/gemini_2.0_pro_model.yaml
# The prompt generator module id for prompt generation.
prompt_generator: 'SQLGenBasePromptGenerator'
#
#
############################################################
### Scorer Related Configs - See /scorers directory for each scorer.
############################################################
scorers:
  exact_match: null
  llmrater:
    model_config: datasets/model_configs/gemini_1.5-pro-002_model.yaml
  returned_sql: null
  set_match: null
#
#
############################################################
### Reporting Related Configs
############################################################
reporting:
  csv:
    output_directory: 'results'
