database_name: db_blog
db: mysql
instance_name: bat-mysql
max_executions_per_minute: 180
password: projects/cloud-db-nl2sql/secrets/bat/versions/1
project_id: cloud-db-nl2sql
region: us-central1
user_name: mysql
