db: alloydb
project_id: cloud-db-nl2sql
region: us-central1
instance_name: my-alloydb-instance
database_name: postgres
user_name: postgres
password: "projects/cloud-db-nl2sql/secrets/my-alloydb-instance/versions/1"

