db: postgres
project_id: cloud-db-nl2sql
region: us-central1
instance_name: nl2sql-synthetic-pg
database_name: air_travel
user_name: nl2sql
password: "projects/cloud-db-nl2sql/secrets/nl2sql-synthetic-pg/versions/1"
max_executions_per_minute: 180
